//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpgCodeExpress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RpgCodeExpress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap application_block {
            get {
                object obj = ResourceManager.GetObject("application_block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Closed {
            get {
                object obj = ResourceManager.GetObject("Folder_Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HtmlHelp2_16x16_DynamicHelp {
            get {
                object obj = ResourceManager.GetObject("HtmlHelp2_16x16_DynamicHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Class {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_CommentRegion {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_CommentRegion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_CopyIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_CopyIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_CutIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_CutIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Debug_Start {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Debug_Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Debug_StopProcess {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Debug_StopProcess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_DeleteIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_DeleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Enum {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Field {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_FindIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_FindIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_FindNextIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_FindNextIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_HelpIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_HelpIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalField {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Literal {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Literal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Method {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_NewDocumentIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_NewDocumentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_NewFolderIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_NewFolderIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_OpenFileIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_OpenFileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PasteIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PasteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateField {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PropertiesIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PropertiesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_RedoIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_RedoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ReplaceIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ReplaceIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_SaveAllIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_SaveAllIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_SaveIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_SaveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_UndoIcon {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_UndoIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap method {
            get {
                object obj = ResourceManager.GetObject("method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RPGCode_Express_Logo__Scaled_ {
            get {
                object obj = ResourceManager.GetObject("RPGCode_Express_Logo__Scaled_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Solution {
            get {
                object obj = ResourceManager.GetObject("Solution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Toolbar_Refresh {
            get {
                object obj = ResourceManager.GetObject("Toolbar_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
